# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

fuel_translation = {
    "Wind": "wind",
    "Wasser": "hydro",
    "Solar": "solar",
    "Braunkohle": "lignite",
    "Biomasse": "biomass",
    "Geothermie": "geothermal",
    "Grubengas": "landfill_gas",
    "andere Gase": "landfill_gas",
    "nicht biogener Abfall": "waste",
    "Steinkohle": "coal",
    "Erdgas": "gas",
    "Mineralölprodukte": "oil",
    "Kernenergie": "nuclear",
    "Speicher": "storage",
}


# SolarLage
mastr_solar_codes = {
    "free_area": "852",
    "roof_top": "853",
    "other": "2484",
    "balcony": "2961",
    "water": "3002",
    "parking_lot": "3058",
}

mastr_solar_azimuth = {
    "695": "0",
    "696": "45",
    "697": "90",
    "698": "135",
    "699": "180",
    "700": "225",
    "701": "270",
    "702": "315",
    "703": "360",
    "704": "-1",
    "806": "90",
    "807": "75",
    "808": "50",
    "809": "30",
    "810": "10",
    "811": "0",
    "802": "100",
    "803": "70",
    "804": "60",
    "805": "50",
    "1535": "100",
}

mastr_storage = {
    "Niederwartha": "591",
    "Bleiloch": "753",
    "Hohenwarte 1": "795",
    "Hohenwarte 2": "2087",
    "Wendefurth": "532",
    "Markersbach": "4018",
    "Geesthacht": "600",
    "Waldeck 1": "478",
    "Waldeck 2": "3428",
    "Bringhausen": "0",
    "Hemfurth": "0",
    "illwerke": "0",
    "Glems": "560",
    "Schwarzenbach": "198",
    "Witznau": "220",
    "Säckingen": "2064",
    "Häusern": "463",
    "Waldshut": "402",
    "Wehr": "6073",
    "Walchenseekraftwerk": "0",
    "Happurg": "900",
    "Schnitzel": "0",
    "Langenprozelten": "950",
    "E2307101": "0",
    "Goldisthal": "8480",
}

# start cost given in [€/MW]
# chi in [t CO2/MWh therm.]
# Set technical parameter corresponding to the type (0, 2000, 2018)
technical_parameter = {
    "coal": {
        0: {
            "maxPower": 100,
            "minPower": 40,
            "gradP": 1,
            "gradM": 1,
            "eta": 36,
            "chi": 0.355,
            "stopTime": 9,
            "runTime": 8,
            "startCost": 60,
            "on": 1,
            "off": 0,
        },
        2000: {
            "maxPower": 100,
            "minPower": 33,
            "gradP": 4,
            "gradM": 4,
            "eta": 40,
            "chi": 0.355,
            "stopTime": 7,
            "runTime": 6,
            "startCost": 60,
            "on": 1,
            "off": 0,
        },
        2018: {
            "maxPower": 100,
            "minPower": 25,
            "gradP": 6,
            "gradM": 6,
            "eta": 45,
            "chi": 0.355,
            "stopTime": 5,
            "runTime": 4,
            "startCost": 60,
            "on": 1,
            "off": 0,
        },
    },
    "gas_combined": {
        0: {
            "maxPower": 100,
            "minPower": 40,
            "gradP": 2,
            "gradM": 2,
            "eta": 45,
            "chi": 0.202,
            "stopTime": 4,
            "runTime": 4,
            "startCost": 60,
            "on": 1,
            "off": 0,
        },
        2000: {
            "maxPower": 100,
            "minPower": 40,
            "gradP": 4,
            "gradM": 4,
            "eta": 55,
            "chi": 0.202,
            "stopTime": 3,
            "runTime": 3,
            "startCost": 60,
            "on": 1,
            "off": 0,
        },
        2018: {
            "maxPower": 100,
            "minPower": 40,
            "gradP": 8,
            "gradM": 8,
            "eta": 65,
            "chi": 0.202,
            "stopTime": 2,
            "runTime": 2,
            "startCost": 60,
            "on": 1,
            "off": 0,
        },
    },
    "gas": {
        0: {
            "maxPower": 100,
            "minPower": 40,
            "gradP": 8,
            "gradM": 8,
            "eta": 40,
            "chi": 0.202,
            "stopTime": 4,
            "runTime": 4,
            "startCost": 20,
            "on": 1,
            "off": 0,
        },
        2000: {
            "maxPower": 100,
            "minPower": 40,
            "gradP": 12,
            "gradM": 12,
            "eta": 45,
            "chi": 0.202,
            "stopTime": 3,
            "runTime": 3,
            "startCost": 20,
            "on": 1,
            "off": 0,
        },
        2018: {
            "maxPower": 100,
            "minPower": 40,
            "gradP": 15,
            "gradM": 15,
            "eta": 50,
            "chi": 0.202,
            "stopTime": 2,
            "runTime": 2,
            "startCost": 20,
            "on": 1,
            "off": 0,
        },
    },
    "lignite": {
        0: {
            "maxPower": 100,
            "minPower": 60,
            "gradP": 1.0,
            "gradM": 1.0,
            "eta": 34,
            "chi": 0.407,
            "stopTime": 9,
            "runTime": 8,
            "startCost": 60,
            "on": 1,
            "off": 0,
        },
        2000: {
            "maxPower": 100,
            "minPower": 50,
            "gradP": 2.5,
            "gradM": 2.5,
            "eta": 40,
            "chi": 0.407,
            "stopTime": 7,
            "runTime": 6,
            "startCost": 60,
            "on": 1,
            "off": 0,
        },
        2018: {
            "maxPower": 100,
            "minPower": 40,
            "gradP": 4.0,
            "gradM": 4.0,
            "eta": 45,
            "chi": 0.407,
            "stopTime": 5,
            "runTime": 4,
            "startCost": 60,
            "on": 1,
            "off": 0,
        },
    },
    "nuclear": {
        0: {
            "maxPower": 100,
            "minPower": 50,
            "gradP": 0.5,
            "gradM": 0.5,
            "eta": 33,
            "chi": 0,
            "stopTime": 22,
            "runTime": 20,
            "startCost": 250,
            "on": 1,
            "off": 0,
        },
        2000: {
            "maxPower": 100,
            "minPower": 45,
            "gradP": 0.5,
            "gradM": 0.5,
            "eta": 35,
            "chi": 0,
            "stopTime": 22,
            "runTime": 15,
            "startCost": 250,
            "on": 1,
            "off": 0,
        },
        2018: {
            "maxPower": 100,
            "minPower": 40,
            "gradP": 0.5,
            "gradM": 0.5,
            "eta": 38,
            "chi": 0,
            "stopTime": 22,
            "runTime": 10,
            "startCost": 250,
            "on": 1,
            "off": 0,
        },
    },
}
