# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

base:
  start_date: 2023-01-01 00:00
  end_date: 2023-12-31 23:00
  time_step: 1h
  save_frequency_hours: 24

  markets_config:
    CRM_pos:
      operator: regelleistung_de-lu
      product_type: capacity_pos
      start_date: 2023-01-01 03:00
      products:
        - duration: 4h
          count: 1
          first_delivery: 22h            # from 08:00 D-1 → 00:00 D
      opening_frequency: 4h
      opening_duration: 1h
      market_mechanism: pay_as_bid
      minimum_bid_price: 0                # €/MW
      maximum_bid_price: 200000           # €/MW
      maximum_bid_volume: 100000          # MW
      volume_tick: 1
      price_unit: €/MW
      volume_unit: MW

    CRM_neg:
      operator: regelleistung_de-lu
      product_type: capacity_neg
      start_date: 2023-01-01 03:00
      products:
        - duration: 4h
          count: 1
          first_delivery: 22h
      opening_frequency: 4h
      opening_duration: 1h
      market_mechanism: pay_as_bid
      minimum_bid_price: 0                # €/MW
      maximum_bid_price: 200000           # €/MW
      maximum_bid_volume: 100000          # MW
      volume_tick: 1
      price_unit: €/MW
      volume_unit: MW

    EOM:
      operator: EPEX_SPOT
      product_type: energy
      start_date: 2023-01-01 05:00        # D-1 gate closure 12:00 local
      products:
        - duration: 1h                   # hourly MTU
          count: 24                       # delivery 00:00–24:00 next day
          first_delivery: 19h            # from 12:00 D-1 → 00:00 D
      opening_frequency: 1d              # daily auction
      opening_duration: 20h              # order entry window (tune as needed)
      market_mechanism: pay_as_clear
      minimum_bid_price: -500             # €/MWh
      maximum_bid_price: 5000             # €/MWh
      maximum_bid_volume: 100000          # MWh
      volume_tick: 0.1                    # MWh
      price_unit: €/MWh
      volume_unit: MWh

    redispatch:
      start_date: 2023-01-01 21:00
      operator: network_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 3h
      opening_frequency: 24h
      opening_duration: 2h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: redispatch
      additional_fields:
        - node
        - min_power
        - max_power
      param_dict:
        network_path: .
        solver: highs
        payment_mechanism: pay_as_bid
        backup_marginal_cost: 10000