example_03:
  start_date: 2018-12-31 22:00
  end_date: 2019-01-11 00:00
  time_step: 1h
#  fuel_prices: fuel_prices.csv
#  temperature: temperature.csv
#  electricity_prices: electricity_prices.csv
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear
