# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

eom:
  start_date: 2024-01-01 00:00
  end_date: 2024-01-01 23:00
  time_step: 60min
  save_frequency_hours: 24

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 60min
          count: 24
          first_delivery: 60min
      opening_frequency: 24h
      opening_duration: 60min
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_bid

  powerplant_units: powerplant_units.csv
  demand_units: demand_units.csv  
  residential_dsm_units: residential_dsm_units.csv
  forecasts: forecasts_df.csv
