base_case_2019:
  start_date: 2018-12-31 20:00
  end_date: 2019-01-11 00:00
  time_step: 1h
  rl_config:
    is_rl_mode: False
    does_training: False
    learning_starts: 10
    train_freq: 100
    gradient_steps: -1
    batch_size: 256
    gamma: 0.999
    training_episodes: 300
  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      start_date: 2018-12-31 23:00
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_volume: 1000000
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

