gantt
   title Market Schedule Simple count 4
   dateFormat  YYY-MM-DD HH:mm
   axisFormat %H:%M
   section First
   Bidding00 EOM          :a1, 2019-01-01 12:00, 1h
   Delivery01 EOM         :2019-01-01 14:00, 1h
   Delivery02 EOM         :2019-01-01 15:00, 1h
   Delivery03 EOM         :2019-01-01 16:00, 1h
   Delivery04 EOM         :2019-01-01 17:00, 1h
   section Second
   Bidding10 EOM          :a2, 2019-01-01 13:00, 1h
   Delivery11 EOM         :2019-01-01 15:00, 1h
   Delivery12 EOM         :2019-01-01 16:00, 1h
   Delivery13 EOM         :2019-01-01 17:00, 1h
   Delivery14 EOM         :2019-01-01 18:00, 1h