dam_BB:
  start_date: 2020-01-01 00:00
  end_date: 2020-01-31 23:00
  time_step: 1h
  save_frequency_hours: Null
  learning_mode: True

  learning_config:
    observation_dimension: 97
    action_dimension: 72
    continue_learning: False
    load_model_path: None
    max_bid_price: 250
    algorithm: matd3
    learning_rate: 0.0001
    training_episodes: 30
    episodes_collecting_initial_experience: 5
    train_freq: 24
    gradient_steps: -1
    batch_size: 64
    gamma: 0.99
    device: cpu
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 5
    order_types: ["SB", "BB"]

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 24h
      opening_frequency: 24h
      opening_duration: 24h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear_complex
      additional_fields:
        - bid_type
        - min_acceptance_ratio


dam_SB:
  start_date: 2037-01-01 00:00
  end_date: 2037-01-31 23:00
  time_step: 1h
  save_frequency_hours: Null
  learning_mode: True

  learning_config:
    observation_dimension: 97
    action_dimension: 72
    continue_learning: False
    load_model_path: None
    max_bid_price: 250
    algorithm: matd3
    learning_rate: 0.0001
    training_episodes: 30
    episodes_collecting_initial_experience: 5
    train_freq: 24
    gradient_steps: -1
    batch_size: 64
    gamma: 0.99
    device: cpu
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 5
    order_types: ["SB"]

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 24h
      opening_frequency: 24h
      opening_duration: 24h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear_complex
      additional_fields:
        - bid_type
        - min_acceptance_ratio

tiny:
  start_date: 2020-01-01 00:00
  end_date: 2020-01-03 23:00
  time_step: 1h
  save_frequency_hours: 24
  learning_mode: True

  learning_config:
    observation_dimension: 97
    action_dimension: 72
    continue_learning: False
    load_model_path: None
    max_bid_price: 250
    algorithm: matd3
    learning_rate: 0.001
    training_episodes: 3
    episodes_collecting_initial_experience: 1
    train_freq: 24
    gradient_steps: -1
    batch_size: 128
    gamma: 0.99
    device: cpu
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 1
    order_types: ["SB", "BB"]

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 24h
      opening_frequency: 24h
      opening_duration: 24h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear_complex
      additional_fields:
        - bid_type
        - min_acceptance_ratio
