# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

EEGH_2024_base:
  start_date: 2024-01-01 00:00
  end_date: 2024-06-29 23:45
  time_step: 15min
  save_frequency_hours: null
  learning_mode: False

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 15min
          count: 1
          first_delivery: 15min
      opening_frequency: 15m
      opening_duration: 15min
      volume_unit: kWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/kWh
      market_mechanism: pay_as_bid_building
      
  learning_config:
    continue_learning: False
    trained_policies_save_path: null
    max_bid_price: 0.13092
    min_bid_price: 0.06288
    algorithm: matd3
    actor_architecture: mlp
    learning_rate: 0.001
    training_episodes: 100
    episodes_collecting_initial_experience: 1
    train_freq: 96h
    gradient_steps: -1
    batch_size: 64
    gamma: 0.99
    device: cuda
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 0.9998
    validation_episodes_interval: 2
    early_stopping_steps: 10
    early_stopping_threshold: 0.05
