# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

base:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-15 00:00
  time_step: 1h
  save_frequency_hours: Null
  learning_mode: True

  learning_config:
    observation_dimension: 50
    action_dimension: 2
    continue_learning: False
    load_model_path: None
    max_bid_price: 100
    algorithm: matd3
    learning_rate: 0.0001
    training_episodes: 30
    episodes_collecting_initial_experience: 5
    train_freq: 24
    gradient_steps: -1
    batch_size: 64
    gamma: 0.99
    device: cpu
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 5

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear


tiny:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-02 00:00
  time_step: 1h
  save_frequency_hours: 24
  learning_mode: True

  learning_config:
    observation_dimension: 50
    action_dimension: 2
    continue_learning: False
    load_model_path: None
    max_bid_price: 100
    algorithm: matd3
    learning_rate: 0.001
    training_episodes: 3
    episodes_collecting_initial_experience: 1
    train_freq: 24
    gradient_steps: -1
    batch_size: 128
    gamma: 0.99
    device: cpu
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 1

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear
