{
 "title": "Assume: Training progress Block bids",
 "description": "Here, the reinforcement learning specific data of assume will be plotted. Especially the process during the learning",
 "time": { "from": "2020-06-30T22:00:00.000Z", "to": "2020-07-31T21:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "simulation",
    "query": "SELECT DISTINCT\nSUBSTRING(m.simulation, 0, LENGTH(m.simulation) +1  - strpos(REVERSE(m.simulation),'_')) AS market_simulation\nFROM rl_params m\nwhere learning_mode is True"
   },
   {
    "name": "rl_unit",
    "label": "rl_unit",
    "query": "SELECT DISTINCT unit\nFROM rl_params\nwhere simulation like '${simulation}' || '_%'"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Welcome to ASSUMES Learning Dashboard\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  power\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 2 },
   "options": {
    "content": "#### Introduction\n\nHere we visualize the results of the reinforcement learning process for the specified units that use a learning strategy. \nReinforcement Learning is a machine learning paradigm where an agent learns to make a sequence of decisions in an environment to maximize a reward signal. \nThe agent explores the environment, takes actions, and receives feedback in the form of rewards. \nThe goal is to learn a strategy (policy) that guides the agent to make actions that lead to the highest cumulative reward over time. \nTo better understand the agent's learning process, we use visualizations that illustrate key aspects of its journey."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  power\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 2 },
   "options": {
    "content": "#### How to use the dashboard\n\nThis interactive tool is designed to help you gain insights into the learning journey of our reinforcement learning (RL) agent. \nTo understand the dashboard take note of the following three points:\n\n##### 1. Division of the Dashboard:\nThe dashboard is divided into two parts. \nThe upper part summarizes the results for all learning units over all simulated episodes. \nThe lower part focuses the results on specific units and episodes, which you can select according to the second point.\n\n\n##### 2. Selection of Metrics and Simulation Subsets:\nThe dashboard is devided in system wide plots and specific plots for certain episodes, timeframes and learning units.\nOn the top of the dashboard, you'll find a list of available choices for the episode of the simualtion and a list of RL units. \nChoose the ones you're interested in by selecting their names in the list. The selected metrics will be displayed on the choice-specific visualization area.\n\n\n##### 3. Interaction with Plots:\nThe plots are interactive. You can zoom in and out, click on data points to view specific details etc.\nIn the upper left corner of each plot you find additional information about the depicted data.\n\nIf you need some guidance for interpreting the results, you can orient yourself on the follwing steps:\n\n1. Understand Learning Trends: \nObserve how reward, exploration, and other metrics change over time. \nLook for trends such as increasing rewards, decreasing episode length, and changes in exploration patterns.\n2. Examine Policy and Action Patterns: \nVisualize the agent's learned policy and action distribution. \nDarker shades indicate preferred actions, while lighter shades show less preferred ones.\n3. Monitor Learning Curve and Loss: \nKeep an eye on the learning curve to see how the agent's performance evolves. \nIf applicable, check the loss curve to understand the convergence of the learning algorithm.\n4. Track Success Rate: \nIf success/failure in an auction is relevant, track the success rate plot to gauge the agent's success in completing a trade. \nNote that sometimes the circumstances might not allow a successfull trade.\n5. Compare Different Strategies: \nIf multiple algorithms or learning parameter sets are available, use the comparison plot to assess their performance. \nSelect the ones you want to compare, and observe how their learning trajectories differ.\n6. Experiment and Learn: \nUse this tool to experiment with different settings and learn about RL agent behavior. \nIt's a great way to develop a deeper understanding of reinforcement learning concepts."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  power\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  { "title": "Simulation Wide Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Average reward of all learning units",
   "type": "barchart",
   "description": "The reward is a measure for the learning agent to determine how desirable (reward > 0) or undesirable (reward < 0) the chosen actions are. This plot shows the rewards averaged over all learning units for each episode. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime,\n  simulation,\n  unit,\n  (episode::float),\n  reward\nFROM rl_params\nwhere simulation like '${simulation}' || '_%'\nand learning_mode is true"
    }
   ]
  },
  {
   "title": "Average evaluation reward of all learning units",
   "type": "barchart",
   "description": "The evaluation reward is the reward for evaluation episodes which are calculated with unseen data.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime,\n  simulation,\n  unit,\n  (episode::float),\n  reward\nFROM rl_params\nwhere simulation like '${simulation}' || '_%'\nand evaluation_mode is true"
    }
   ]
  },
  {
   "title": "Cumulative avergage REWARD over all Units per episode",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "-- this query creates a cumulative sum of the reward until now\r\nSELECT \r\n  $__timeGroupAlias(datetime,$__interval),\r\n  'episode ' || episode AS \"episode\",\r\n  sum(sum(reward)) OVER (PARTITION BY episode ORDER BY datetime) AS \"reward\"\r\nFROM\r\n  rl_params\r\nWHERE\r\n  $__timeFilter(datetime) \r\n  and simulation like '${simulation}' || '_%'\r\nGROUP BY 1, datetime, episode\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cumulative avergage PROFIT over all Units per episode",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(datetime,$__interval),\r\n  'episode ' || episode AS \"episode\",\r\n  sum(sum(profit)) OVER (PARTITION BY episode ORDER BY datetime) AS \"profit\"\r\nFROM\r\n  rl_params\r\nWHERE\r\n  $__timeFilter(datetime)\r\n  and simulation like '${simulation}' || '_%'\r\nGROUP BY 1, datetime, episode\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Accepted Volume Ratio for all Units  ",
   "type": "timeseries",
   "description": "The accepted volume ratio is the ratio between the accepted volume and the offered volume.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(start_time,$__interval),\r\n  avg(accepted_volume/volume) filter(where volume !=0) AS \"accepted_volume\"\r\nFROM market_orders\r\nWHERE\r\n  $__timeFilter(start_time)\r\n  and simulation = '$simulation'\r\nGROUP BY 1, start_time\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Exemplary Subset of RL Parameters",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "SELECT \r\n*\r\nFROM rl_params\r\nwhere simulation like '$simulation'\r\nlimit 50;\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Bid volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  unit_id,\r\n  ((sum(accepted_volume) filter(Where bid_type = 'BB')) / NULLIF(sum(accepted_volume), 0)) *100 as \"block bid share\"\r\nFROM market_orders\r\nWHERE\r\n  simulation = '$simulation'\r\n  AND unit_id in ($rl_unit)\r\nGROUP BY unit_id\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Unit-specific and Episodic Data ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "repeat": "rl_unit"
  },
  {
   "title": "Avg. reward of unit $rl_unit",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime,\n  simulation,\n  unit,\n  (episode::float),\n  reward\nFROM rl_params\nwhere simulation like '${simulation}' || '_%' AND\n      unit in ($rl_unit)"
    }
   ]
  },
  {
   "title": "Avg. regret of unit $rl_unit",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime,\n  simulation,\n  unit,\n  (episode::float),\n  regret\nFROM rl_params\nwhere simulation like '${simulation}' || '_%' AND\n      unit in ($rl_unit)"
    }
   ]
  },
  {
   "title": "Avg.evaluation  reward of unit $rl_unit",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime,\n  simulation,\n  unit,\n  (episode::float),\n  reward\nFROM rl_params\nwhere simulation like '${simulation}' || '_%' AND\n      unit  in ($rl_unit) and evaluation_mode is True"
    }
   ]
  },
  {
   "title": "Total profit of unit $rl_unit",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime,\n  simulation,\n  unit,\n  (episode::float),\n  profit\nFROM rl_params\nwhere simulation like '${simulation}' || '_%' AND\n      unit in ($rl_unit)"
    }
   ]
  },
  {
   "title": "Bid price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(price_data.\"time\", $__interval),\r\n  price_data.\"min_price\" AS \"price_inflex\",\r\n  price_data.\"max_price\" AS \"price_flex\",\r\n  bid_type\r\nFROM\r\n(\r\n  SELECT\r\n    start_time as \"time\",\r\n    MIN(price) AS \"min_price\",\r\n    MAX(price) AS \"max_price\",\r\n    bid_type\r\n  FROM market_orders\r\n  WHERE\r\n    $__timeFilter(start_time) AND\r\n    simulation = '$simulation' AND\r\n    unit_id in ($rl_unit)\r\n  GROUP BY 1, bid_type\r\n) price_data\r\nORDER BY 1, bid_type"
    }
   ]
  },
  {
   "title": "Normalized Action values - P_inflex",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  actions_0 AS \"action_Pinflex\",\n  actions_0+exploration_noise_0 AS \"noisy_action_Pinflex\",\n  simulation AS \"simulation\"\nFROM rl_params\nWHERE\n  $__timeFilter(datetime) AND\n  simulation = '$simulation' AND\n  unit in ($rl_unit)\n\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Bid volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(start_time,$__interval),\r\n  sum(volume) AS \"Bid volume:\",\r\n  bid_type\r\nFROM market_orders\r\nWHERE\r\n  $__timeFilter(start_time) AND\r\n  simulation = '$simulation'\r\n  AND unit_id in ($rl_unit)\r\nGROUP BY 1, unit_id, volume, bid_type\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Normalized Action values - P_flex",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  round(CAST(actions_1 AS numeric), 2) AS \"action_Pflex\",\n  round(CAST(actions_1 AS numeric), 2)+round(CAST(exploration_noise_1 AS numeric), 2) AS \"noisy_action_Pflex\",\n  simulation AS \"simulation\"\nFROM rl_params\nWHERE\n  $__timeFilter(datetime) AND\n  simulation = '$simulation' AND\n  unit in ($rl_unit)\n\nORDER BY 1"
    }
   ]
  }
 ]
}