{
 "title": "ASSUME: Inspect Dmas Links",
 "time": { "from": "2019-01-01T00:00:00.003Z", "to": "2019-01-03T00:00:00.762Z" },
 "templating": {
  "list": [
   {
    "name": "simulation",
    "query": "SELECT simulation\nFROM market_meta"
   },
   {
    "name": "market",
    "query": "SELECT \n  market_id\nFROM market_meta\nwhere simulation='$simulation'\ngroup by market_id ;"
   },
   {
    "name": "Gen_Units",
    "query": "SELECT index\nFROM power_plant_meta\nwhere simulation = '$simulation';"
   },
   {
    "name": "Demand_Units",
    "query": "SELECT index\nFROM demand_meta\nwhere simulation = '$simulation';"
   },
   {
    "name": "Storage_Units",
    "query": "SELECT index\nFROM storage_meta\nwhere simulation = '$simulation';"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview Dashboard",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Welcome to our ASSUME demo\n\nThis is the Grafana Dashboard which makes interacting with the simulation data very easy."
   }
  },
  {
   "title": "Market Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
     "options": {
      "content": "# Market-specific Data\n\nData specific for the market depending on the choice made at te top of the panel\n\n"
     }
    },
    {
     "title": "Market Summary $market",
     "type": "timeseries",
     "description": "Overview of market results for the chossen market",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(product_start, $__interval),\n  avg(demand_volume) AS \"Demand volume\",\n  avg(supply_volume) AS \"Supply volume\",\n  avg(price) AS \"Price\",\n  node\nFROM market_meta\nWHERE (\"simulation\" LIKE '$simulation') AND \"market_id\" ='$market' AND $__timeFilter(product_start)\nGROUP BY 1, market_id, simulation, node\nORDER BY 1, node;\n"
      }
     ]
    },
    {
     "title": "Merit Order $market",
     "type": "xychart",
     "description": "Big Point Size is demand match. Unused generation after that point",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  sum(volume::float) OVER (PARTITION BY market_id ORDER BY price asc, unit_id) AS \"Volume\",\n  price::float AS \"Price\", unit_id,\n  1/(volume - accepted_volume +1)/2 as size\n  --'rgba(255,255,255,1)' as delta\nFROM market_orders\nWHERE\n  \n  start_time = (select min(start_time) from market_orders where market_id = '$market' AND\n  simulation = '$simulation' and $__timeFilter(start_time))\n  AND\n  volume > 0 AND\n  --accepted_volume != 0 AND\n  market_id = '$market' AND\n  simulation = '$simulation'\nGROUP BY unit_id, volume, accepted_volume, price, market_id --, bid_id\nORDER BY price asc"
      },
      {
       "rawSql": "SELECT\n  -sum(volume::float) OVER (PARTITION BY market_id ORDER BY accepted_price asc, unit_id) AS \"Volume\",\n  accepted_price::float AS \"Price\", unit_id,\n  10 as size\nFROM market_orders\nWHERE\n  \n  start_time = (select min(start_time) from market_orders where market_id = '$market' AND\n  simulation = '$simulation' and $__timeFilter(start_time))\n  AND\n  volume < 0 AND\n  --accepted_volume != 0 AND\n  market_id = '$market' AND\n  simulation = '$simulation'\nGROUP BY unit_id, volume, accepted_volume, accepted_price, market_id\nORDER BY accepted_price asc"
      }
     ]
    },
    {
     "title": "Average Accepted Bid Price",
     "type": "timeseries",
     "description": "Bid prices of accepted bids per unit in the chosen market",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "€/MW" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(start_time,$__interval),\n  avg(accepted_price::float) AS \"Price\", unit_id\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  market_id = '$market' AND\n  simulation = '$simulation'\nGROUP BY 1, unit_id --, bid_id\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Average Accepted Bid Volume",
     "type": "timeseries",
     "description": "Accepted Volume  per unit in chosen market",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(start_time,$__interval),\n  avg(accepted_volume) AS \"Volume\", unit_id\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  market_id = '$market' AND\n  simulation = '$simulation'\nGROUP BY 1, unit_id, bid_id\nORDER BY 1"
      }
     ]
    }
   ]
  },
  { "title": "Key performance indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Cost and Volume",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  simulation,\n  sum(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'total_cost') as \"Total cost\",\n  sum(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'total_volume') as \"Total volume\"\nFROM kpis\nWHERE simulation = '$simulation'\ngroup by simulation"
    }
   ]
  },
  {
   "title": "Key indicators",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  simulation,\n  avg(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'avg_price') as avg_price,\n  sum(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'total_cost') as total_cost,\n  sum(round(CAST(value AS numeric), 2)*1000)  FILTER (WHERE variable = 'total_volume') as total_volume\nFROM kpis\ngroup by simulation\nORDER BY simulation"
    }
   ]
  },
  {
   "title": "Installed Generation Capacities",
   "type": "piechart",
   "description": "Shows installed capacities in the simulation based on the fuel type",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() as time_sec,\n  SUM(max_power),\n  technology\nFROM power_plant_meta\nWHERE \"simulation\" LIKE '$simulation'\nGROUP BY technology, simulation;\n\n\n"
    }
   ]
  },
  { "title": "Generation units $Gen_Units", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
   "options": {
    "content": "# Unit Specific Data\n\nFor the chosen market and the chosen unit here the dispatch is displayed."
   }
  },
  {
   "title": "Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  avg(power) AS \"Market dispatch\",\n  concat(unit_id, ' - ', market_id) as \"unit\"\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  simulation = '$simulation' AND\n  unit_id in ($Gen_Units)\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(power) AS \"Actual dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(time) AND\n  simulation = '$simulation' AND\n  unit in ($Gen_Units)\nGROUP BY 1, unit\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Chosen Unit Specifications",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "options": {
    "content": "### General Information\n\nName: {{index}} <br>\nTechnology: {{technology}} <br>\n\n### Technical Specifications\nEmissions: {{emission_factor}} t/MWh <br>\nMaximum Power: {{max_power}} MW <br>\nMinimum Power: {{min_power}} MW <br>\nEfficiency: {{efficiency}} <br>\n\n##### Unit Operator: {{unit_operator}}\n  "
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM power_plant_meta\nWHERE index in ($Gen_Units) and simulation = '$simulation'\n"
    }
   ]
  },
  {
   "title": "Bid Prices",
   "type": "timeseries",
   "description": "Bid prices of accepted bids per unit in the chosen market",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(start_time,$__interval),\r\n  avg(accepted_price::float) AS \"Accepted price:\",\r\n  avg(price) AS \"Bid price:\",\r\n  concat(unit_id, ' - ', market_id) as \"unit_id\"\r\nFROM market_orders\r\nWHERE\r\n  $__timeFilter(start_time) AND\r\n  unit_id in ($Gen_Units) AND\r\n  simulation = '$simulation'\r\nGROUP BY 1, unit_id, market_id\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Bid volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(start_time,$__interval),\r\n  sum(accepted_volume) AS \"Accepted volume:\",\r\n  avg(volume) AS \"Bid volume:\",\r\n  concat(unit_id, ' - ', market_id, ' - ', block_id) as \"unit_id\"\r\nFROM market_orders\r\nWHERE\r\n  $__timeFilter(start_time) AND\r\n  unit_id in ($Gen_Units) AND\r\n  simulation = '$simulation'\r\nGROUP BY 1, unit_id, market_id, block_id\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Financial Overview ${__from:date:YYYY-MM-DD} until ${__to:date:YYYY-MM-DD}",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(time,$__interval),\r\n  energy_cashflow AS \"Cashflow\",\r\n  energy_marginal_costs AS \"Production costs\",\r\n  energy_cashflow - energy_marginal_costs AS \"Profit\",\r\n  unit\r\nFROM unit_dispatch\r\nWHERE\r\n  $__timeFilter(time) AND\r\n  simulation = '$simulation' AND\r\n  unit in ($Gen_Units)\r\nGROUP BY 1, unit, energy_cashflow, energy_marginal_costs\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Financial Overview ${__from:date:YYYY-MM-DD} until ${__to:date:YYYY-MM-DD}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(time,$__interval),\r\n  energy_cashflow AS \"Cashflow\",\r\n  energy_marginal_costs AS \"Production costs\",\r\n  energy_cashflow - energy_marginal_costs AS \"Profit\",\r\n  unit\r\nFROM unit_dispatch\r\nWHERE\r\n  $__timeFilter(time) AND\r\n  simulation = '$simulation' AND\r\n  unit in ($Gen_Units)\r\nGROUP BY 1, unit, energy_cashflow, energy_marginal_costs\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Demand units data $Demand_Units",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unitwise Dispatch",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"Market dispatch\",\n  concat(unit_id, ' - ', market_id) as unit\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  simulation = '$simulation' AND\n  unit_id in ($Demand_Units)\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  power AS \"Actual dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(time) AND\n  simulation = '$simulation' AND\n  unit in ($Demand_Units)\nGROUP BY 1, unit, power\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Chosen Unit Specifications",
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 54 },
     "options": {
      "content": "### General Information\n\nName: {{index}} <br>\nTechnology: {{technology}} <br>\n\n### Technical Specifications\nEmissions: {{emission_factor}} t/MWh <br>\nMaximum Power: {{max_power}} MW <br>\nMinimum Power: {{min_power}} MW <br>\nEfficiency: {{efficiency}} <br>\n\n##### Unit Operator: {{unit_operator}}\n  "
     },
     "targets": [
      {
       "rawSql": "SELECT * FROM demand_meta\nWHERE index in ($Demand_Units) and simulation = '$simulation'\n"
      }
     ]
    },
    {
     "title": "Bid Prices",
     "type": "timeseries",
     "description": "Bid prices of accepted bids per unit in the chosen market",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroupAlias(start_time,$__interval),\r\n  avg(accepted_price::float) AS \"Accepted price:\",\r\n  price AS \"Bid price:\",\r\n  concat(unit_id, ' - ', market_id) as \"unit_id\"\r\nFROM market_orders\r\nWHERE\r\n  $__timeFilter(start_time) AND\r\n  unit_id in ($Demand_Units) AND\r\n  simulation = '$simulation'\r\nGROUP BY 1, unit_id, market_id, price\r\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total Cost of Energy Dispatch",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroupAlias(time,$__interval),\r\n  -energy_cashflow AS \"Cashflow\",\r\n  unit\r\nFROM unit_dispatch d\r\nWHERE\r\n  $__timeFilter(time) AND\r\n  d.simulation = '$simulation' AND\r\n  unit in ($Demand_Units)\r\nGROUP BY 1, unit, energy_cashflow, power\r\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Bid volume",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroupAlias(start_time,$__interval),\r\n  -avg(accepted_volume) AS \"Accepted volume:\",\r\n  -avg(volume) AS \"Bid volume:\",\r\n  concat(unit_id, ' - ', market_id) as \"unit_id\"\r\nFROM market_orders\r\nWHERE\r\n  $__timeFilter(start_time) AND\r\n  unit_id in ($Demand_Units) AND\r\n  simulation = '$simulation'\r\nGROUP BY 1, unit_id, market_id\r\nORDER BY 1\r\n"
      }
     ]
    },
    {
     "title": "weighted average Price in €/MW for Demand $Demand_Units",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "€/MW" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  sum(energy_cashflow)/sum(power) as \"Price per MW\",\n  unit\nFROM unit_dispatch d\nWHERE\n  $__timeFilter(time) AND\n  d.simulation = '$simulation' AND\n  unit in ($Demand_Units)\nGROUP BY unit\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total dispatched Volume",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroupAlias(time,$__interval),\r\n  -power*1e3 as \"Volume\",\r\n  unit\r\nFROM unit_dispatch d\r\nWHERE\r\n  $__timeFilter(time) AND\r\n  d.simulation = '$simulation' AND\r\n  unit in ($Demand_Units)\r\nGROUP BY 1, unit, energy_cashflow, power\r\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Energy Related Cashflow",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroupAlias(time,$__interval),\r\n  -energy_cashflow AS \"Cashflow:\",\r\n  -energy_marginal_costs AS \"Production costs:\",\r\n  energy_cashflow - energy_marginal_costs AS \"Profit\",\r\n  unit\r\nFROM unit_dispatch\r\nWHERE\r\n  $__timeFilter(time) AND\r\n  simulation = '$simulation' AND\r\n  unit in ($Demand_Units)\r\nGROUP BY 1, unit, energy_cashflow, energy_marginal_costs\r\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage units data $Storage_Units",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Dispatch",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"Market dispatch\",\n  unit_id,\n  market_id\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  simulation = '$simulation' AND\n  unit_id in ($Storage_Units)\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  power AS \"Actual dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(time) AND\n  simulation = '$simulation' AND\n  unit in ($Storage_Units)\nGROUP BY 1, unit, power\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Chosen Unit Specifications",
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 55 },
     "options": {
      "content": "### General Information\n\nName: {{index}} <br>\nTechnology: {{technology}} <br>\n\n### Technical Specifications\nEmissions: {{emission_factor}} t/MWh <br>\nMaximum Power Disharge: {{max_power_discharge}} MW <br>\nMinimum Power Discharge: {{min_power_discharge}} MW <br>\nEfficiency Discharge: {{efficiency_discharge}} <br>\n\nMaximum Power Charge: {{max_power_charge}} MW <br>\nMinimum Power Charge: {{min_power_charge}} MW <br>\nEfficiency Charge: {{efficiency_charge}} <br>\n\n##### Unit Operator: {{unit_operator}}\n  "
     },
     "targets": [
      {
       "rawSql": "SELECT * FROM storage_meta\nWHERE index in ($Storage_Units) and simulation = '$simulation'\n"
      }
     ]
    },
    {
     "title": "State of Charge",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "mwatth" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroupAlias(time,$__interval),\r\n  SOC AS \"State of Charge\",\r\n  unit\r\nFROM unit_dispatch\r\nWHERE\r\n  $__timeFilter(time) AND\r\n  simulation = '$simulation' AND\r\n  unit in ($Storage_Units)\r\nGROUP BY 1, unit, SOC\r\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Bid Prices",
     "type": "timeseries",
     "description": "Bid prices of accepted bids per unit in the chosen market",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroupAlias(start_time,$__interval),\r\n  CASE WHEN avg(accepted_volume) >= 0 THEN avg(accepted_price::float) END AS \"Accepted price Discharge\",\r\n  CASE WHEN avg(accepted_volume) < 0 THEN avg(accepted_price::float) END AS \"Accepted price Charge\",\r\n  CASE WHEN avg(volume) >= 0 THEN avg(price) END AS \"Bid price Discharge\",\r\n  CASE WHEN avg(volume) < 0 THEN avg(price) END AS \"Bid price Charge\",\r\n  concat(unit_id, ' - ', market_id) as \"unit_id\"\r\nFROM market_orders\r\nWHERE\r\n  $__timeFilter(start_time) AND\r\n  unit_id in ($Storage_Units) AND\r\n  simulation = '$simulation'\r\nGROUP BY 1, unit_id, market_id\r\nORDER BY 1\r\n"
      }
     ]
    },
    {
     "title": "Bid volume",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroupAlias(start_time,$__interval),\r\n  avg(accepted_volume) AS \"Accepted volume:\",\r\n  CASE WHEN avg(volume) < 0 THEN avg(volume) END AS \"Bid volume charge:\",\r\n  CASE WHEN avg(volume) >= 0 THEN avg(volume) END AS \"Bid volume discharge:\",\r\n  concat(unit_id, ' - ', market_id) as \"unit_id\"\r\nFROM market_orders\r\nWHERE\r\n  $__timeFilter(start_time) AND\r\n  unit_id in ($Storage_Units) AND\r\n  simulation = '$simulation'\r\nGROUP BY 1, unit_id, market_id\r\nORDER BY 1\r\n"
      }
     ]
    },
    {
     "title": "Financial Overview ${__from:date:YYYY-MM-DD} until ${__to:date:YYYY-MM-DD}",
     "type": "stat",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroupAlias(time,$__interval),\r\n  energy_cashflow AS \"Cashflow\",\r\n  energy_marginal_costs AS \"Production costs\",\r\n  energy_cashflow - energy_marginal_costs AS \"Profit\",\r\n  unit\r\nFROM unit_dispatch\r\nWHERE\r\n  $__timeFilter(time) AND\r\n  simulation = '$simulation' AND\r\n  unit in ($Storage_Units)\r\nGROUP BY 1, unit, energy_cashflow, energy_marginal_costs\r\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Financial Overview ${__from:date:YYYY-MM-DD} until ${__to:date:YYYY-MM-DD}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  $__timeGroupAlias(time,$__interval),\r\n  energy_cashflow AS \"Cashflow\",\r\n  energy_marginal_costs AS \"Production costs\",\r\n  energy_cashflow - energy_marginal_costs AS \"Profit\",\r\n  unit\r\nFROM unit_dispatch\r\nWHERE\r\n  $__timeFilter(time) AND\r\n  simulation = '$simulation' AND\r\n  unit in ($Storage_Units)\r\nGROUP BY 1, unit, energy_cashflow, energy_marginal_costs\r\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}