{
 "title": "ASSUME Comparison Block Bids",
 "time": { "from": "2020-01-19T23:00:00.000Z", "to": "2020-01-26T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "Gen_Units",
    "query": "SELECT index\nFROM power_plant_meta\nwhere simulation in ($simulation);"
   },
   {
    "name": "Demand_Units",
    "query": "SELECT index\nFROM demand_meta\nwhere simulation in ($simulation);"
   },
   {
    "name": "Storage_Units",
    "query": "SELECT index\nFROM storage_meta\nwhere simulation in ($simulation);"
   },
   {
    "name": "simulation",
    "query": "SELECT \n  simulation\nFROM power_plant_meta\ngroup by simulation;"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview Dashboard",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Welcome to our ASSUME demo\n\nThis is the Grafana Dashboard which makes interacting with the simulation data very easy."
   }
  },
  { "title": "Market Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "# Market-specific Data\n\nData specific for the market depending on the choice made at te top of the panel\n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  product_start AS \"time\",\n  supply_volume\nFROM market_meta\nWHERE\n  $__timeFilter(product_start)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Market Summary EOM",
   "type": "timeseries",
   "description": "Overview of market results for the chossen market",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  product_start AS \"time\",\n  simulation as \"simulation\",\n  supply_volume AS \"Supply Volume\"\nFROM market_meta\nWHERE $__timeFilter(product_start) and\n  simulation in ($simulation)\nGROUP BY simulation, product_start, supply_volume\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  product_start AS \"time\",\n  simulation as \"simulation\",\n  price AS \"Price\"\nFROM market_meta\nWHERE $__timeFilter(product_start) and\n  simulation in ($simulation)\nGROUP BY simulation, product_start, price\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Accepted Bid Prices",
   "type": "timeseries",
   "description": "Bid prices of accepted bids per unit in the chosen market",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "€/MW" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_time,$__interval),\n  price AS \" \",\n  unit_id AS \"unit_id\",\n  simulation as \"simulation\"\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  simulation in ($simulation) AND\n  unit_id not in ('', ' ')\nGROUP BY 1, unit_id, start_time, price, simulation\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(product_start,$__interval),\n  price as \"MCP\",\n  simulation as \"simulation\"\nFROM market_meta\nWHERE\n  $__timeFilter(product_start) AND\n  simulation in ($simulation)\nGroup by 1, product_start, price, simulation\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Accepted Bid Volume",
   "type": "timeseries",
   "description": "Accepted Volume  per unit in chosen market",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_time,$__interval),\n  sum(accepted_volume) AS \" \",\n  unit_id AS \"unit_id\",\n  simulation as \"simulation\"\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  simulation in ($simulation)\nGROUP BY 1, unit_id, start_time, simulation\nORDER BY 1\n"
    }
   ]
  },
  { "title": "Key performance indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Cost and Volume",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT summary.simulation, summary.\"Total cost\",\nsummary.\"Total volume\",\norders.\"Social welfare producers\"\nFrom (\nSELECT\n  simulation,\n  sum(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'total_cost') as \"Total cost\",\n  sum(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'total_volume') as \"Total volume\"\nFROM kpis\nwhere simulation in ($simulation)\ngroup by simulation\nORDER BY simulation) summary\njoin (\nSELECT\n  simulation,\n  sum(round(CAST((accepted_price - price) * accepted_volume AS numeric), 2)) filter(where accepted_volume>0) as \"Social welfare producers\"\nFROM market_orders\nwhere simulation in ($simulation)\ngroup by simulation\nORDER BY simulation) orders on orders.simulation = summary.simulation\n"
    }
   ]
  },
  {
   "title": "Key indicators",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 7, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  simulation,\n  sum(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'avg_price') as avg_price,\n  sum(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'total_cost') as total_cost,\n  sum(round(CAST(value AS numeric), 2)*1000)  FILTER (WHERE variable = 'total_volume') as total_volume\n  \nFROM kpis\nwhere variable in ('total_cost', 'total_volume', 'avg_price')\ngroup by simulation\nORDER BY simulation"
    },
    {
     "rawSql": "SELECT\n  simulation,\n  sum(round(CAST((accepted_price - price) * accepted_volume AS numeric), 2)) filter(where accepted_volume > 0) as welfare_producers,\n  -sum(round(CAST((accepted_price - price) * accepted_volume AS numeric), 2)) filter(where accepted_volume < 0) as welfare_consumers,\n  -sum(round(CAST(price * accepted_volume AS numeric), 2)) as social_welfare,\n  (sum(round(CAST(accepted_volume AS numeric), 2)) filter(where unit_id in ('Wind onshore', 'Wind offshore', 'Solar', 'Hydro', 'Biomass'))\n  /\n  sum(round(CAST(accepted_volume AS numeric), 6)) filter(where accepted_volume > 0)) as ren_share\nFROM market_orders\nGROUP BY simulation\nORDER BY simulation"
    },
    {
     "rawSql": "SELECT\n  simulation,\n  stddev(round(CAST(price AS numeric), 2)) as MCP_std\nFROM market_meta\nGROUP BY simulation\nORDER BY simulation"
    }
   ]
  },
  {
   "title": "Installed Generation Capacities",
   "type": "piechart",
   "description": "Shows installed capacities in the simulation based on the fuel type",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT On (index)\n  NOW() as time_sec,\n  SUM(max_power/2),\n  technology\nFROM power_plant_meta\nWHERE \"simulation\" in ($simulation)\nGROUP BY technology, index\n\n\n\n"
    }
   ]
  },
  { "title": "Generation units $Gen_Units", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "# Unit Specific Data\n\nFor the chosen market and the chosen unit here the dispatch is displayed."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  volume\nFROM demand_meta\nWHERE\n  $__timeFilter(\"Timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Key indicators",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  simulation,\n  sum(round(CAST(costs AS numeric), 2)) as Total_costs,\n  sum(round(CAST(energy_cashflow AS numeric), 2)) as Total_revenues,\n  sum(round(CAST(profits AS numeric), 2)) as Total_profits,\n  sum(round(CAST(power AS numeric), 2)) as Total_power\nFROM unit_dispatch\nwhere \n  unit in ($Gen_Units) and\n  simulation in ($simulation)\nGROUP BY simulation\nORDER BY simulation"
    }
   ]
  },
  {
   "title": "Chosen Unit Specifications",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 23, "w": 6, "x": 18, "y": 53 },
   "options": {
    "content": "### General Information\n\nName: {{index}} <br>\nTechnology: {{technology}} <br>\n\n### Technical Specifications\nEmissions: {{emission_factor}} t/MWh <br>\nMaximum Power: {{max_power}} MW <br>\nMinimum Power: {{min_power}} MW <br>\nEfficiency: {{efficiency}} <br>\n\n##### Unit Operator: {{unit_operator}}\n  "
   },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT On (index) * FROM power_plant_meta\nWHERE index in ($Gen_Units) and simulation in ($simulation)\n"
    }
   ]
  },
  {
   "title": "Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  power AS \"dispatch\",\n  unit,\n  simulation\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  unit in ($Gen_Units) AND\n  simulation in ($simulation)\nGROUP BY 1, unit, power, simulation\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Offered Bid Prices and Volume",
   "type": "timeseries",
   "description": "Bid prices of accepted bids per unit in the chosen market",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(start_time,$__interval),\n  max(price) AS \"price\",\n  sum(round(CAST(volume as numeric), 2)) AS \"volume\",\n  unit_id as \"unit_id\",\n  simulation,\n  bid_type\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  unit_id in ($Gen_Units) AND\n  simulation in ($simulation)\nGROUP BY 1, bid_type, simulation, unit_id\nOrder by 1"
    }
   ]
  },
  {
   "title": "Unitwise breaking constraints - not dispatched power",
   "type": "timeseries",
   "description": "Market outcome - actual dispatch respecting ramping unit constraints",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "Select (market_outcome.\"Accepted Volume\" - actual_dispatch.power)  as \"mismatch\",\n  market_outcome.unit_id,\n  actual_dispatch.\"time\",\n  market_outcome.simulation\nFrom(\nSELECT\n  $__timeGroupAlias(index,$__interval),\n  power,\n  unit,\n  simulation\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  unit in ($Gen_Units) AND\n  simulation in ($simulation)\nGROUP BY 1, unit, power, simulation\nORDER BY 1) actual_dispatch\nleft join(\nSELECT\n  $__timeGroupAlias(start_time,$__interval),\n  sum(accepted_volume) as \"Accepted Volume\",\n  simulation,\n  unit_id\nFROM market_orders\nWhere\n  $__timeFilter(start_time) AND\n  unit_id in ($Gen_Units) AND\n  simulation in ($simulation)\nGROUP BY 1, unit_id, simulation\nORDER BY 1\n) market_outcome on (market_outcome.time = actual_dispatch.time AND\n  actual_dispatch.unit = market_outcome.unit_id AND\n  actual_dispatch.simulation = market_outcome.simulation)\n\n"
    }
   ]
  },
  {
   "title": "Accepted volumes",
   "type": "barchart",
   "description": "Offered volume is incorrect, because only accepted and partly accepted orders are saved",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "MWh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  orders.\"id\",\n  orders.\"offered_volume\",\n  orders.\"accepted_volume\",\n  units.\"dispatched_volume\"\nfrom(\nSELECT\n  sum(round(CAST(volume AS numeric), 2)) as \"offered_volume\",\n  sum(round(CAST(accepted_volume AS numeric), 2)) as \"accepted_volume\",\n  simulation,\n  unit_id,\n  concat(unit_id, '_', simulation) as \"id\"\nFROM market_orders\nWHERE\n  simulation in ($simulation) AND\n  unit_id IN ($Gen_Units)\nGROUP BY unit_id, simulation) orders\njoin\n(\nSELECT\n  sum(round(CAST(power AS numeric), 2)) AS \"dispatched_volume\",\n  simulation,\n  unit,\n  concat(unit, '_', simulation) as \"id\"\nFROM unit_dispatch\nWHERE\n  simulation in ($simulation) AND\n  unit IN ($Gen_Units)\nGROUP BY unit, simulation\n) units on orders.\"id\" = units.\"id\""
    }
   ]
  },
  {
   "title": "Demand units data $Demand_Units",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 96 },
   "options": {
    "content": "# Unit Specific Data\n\nFor the chosen market and the chosen unit here the dispatch is displayed."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  volume\nFROM demand_meta\nWHERE\n  $__timeFilter(\"Timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"power\",\n  unit_id,\n  simulation\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  simulation in ($simulation) AND\n  unit_id in ($Demand_Units)\nGROUP BY 1, unit_id, power, simulation\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  power AS \"dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  simulation = '$simulation_comp' AND\n  unit in ($Demand_Units)\nGROUP BY 1, unit, power\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Chosen Unit Specifications",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 99 },
   "options": {
    "content": "### General Information\n\nName: {{index}} <br>\nTechnology: {{technology}} <br>\n\n### Technical Specifications\nEmissions: {{emission_factor}} t/MWh <br>\nMaximum Power: {{max_power}} MW <br>\nMinimum Power: {{min_power}} MW <br>\nEfficiency: {{efficiency}} <br>\n\n##### Unit Operator: {{unit_operator}}\n  "
   },
   "targets": [
    {
     "rawSql": "SELECT distinct on (index) * FROM demand_meta\nWHERE index in ($Demand_Units) and simulation in ($simulation)\n"
    }
   ]
  },
  {
   "title": "Storage units data $Storage_Units",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "repeat": "Storage_Units"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 109 },
   "options": {
    "content": "# Unit Specific Data\n\nFor the chosen market and the chosen storage unit here the dispatch is displayed."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Timestamp\" AS \"time\",\n  volume\nFROM demand_meta\nWHERE\n  $__timeFilter(\"Timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Storage Dispatch Difference",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"power\",\n  unit_id,\n  simulation\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  simulation in ($simulation) AND\n  unit_id in ($Storage_Units)\nGROUP BY 1, unit_id, power, simulation\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(index,$__interval),\n  power AS \"dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  simulation = '$simulation_comp' AND\n  unit in ($Storage_Units)\nGROUP BY 1, unit, power\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Chosen Unit Specifications",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 112 },
   "options": {
    "content": "### General Information\n\nName: {{index}} <br>\nTechnology: {{technology}} <br>\n\n### Technical Specifications\nEmissions: {{emission_factor}} t/MWh <br>\nMaximum Power Disharge: {{max_power_discharge}} MW <br>\nMinimum Power Discharge: {{min_power_discharge}} MW <br>\nEfficiency Discharge: {{efficiency_discharge}} <br>\n\nMaximum Power Charge: {{max_power_charge}} MW <br>\nMinimum Power Charge: {{min_power_charge}} MW <br>\nEfficiency Charge: {{efficiency_charge}} <br>\n\n##### Unit Operator: {{unit_operator}}\n  "
   },
   "targets": [
    {
     "rawSql": "SELECT distinct on (index) * FROM storage_meta\nWHERE index in ($Storage_Units) and simulation in ($simulation)\n"
    }
   ]
  }
 ]
}