{
 "title": "ASSUME: Compare scenarios",
 "time": { "from": "2019-02-28T23:00:00.000Z", "to": "2019-04-01T21:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "simulation",
    "query": "SELECT \n  simulation\nFROM power_plant_meta\ngroup by simulation;"
   },
   {
    "name": "simulation_comp",
    "query": "SELECT \n  simulation\nFROM power_plant_meta\ngroup by simulation;"
   },
   {
    "name": "market",
    "query": "SELECT \n  market_id\nFROM market_meta\nwhere simulation='$simulation'\ngroup by market_id ;"
   },
   {
    "name": "Gen_Units",
    "query": "SELECT index\nFROM power_plant_meta\nwhere simulation = '$simulation';"
   },
   {
    "name": "Demand_Units",
    "query": "SELECT index\nFROM demand_meta\nwhere simulation = '$simulation';"
   },
   {
    "name": "Storage_Units",
    "query": "SELECT index\nFROM storage_meta\nwhere simulation = '$simulation';"
   },
   {
    "name": "simulation_start",
    "query": "SELECT  min(start_time) FROM market_orders WHERE simulation = '$simulation' "
   },
   {
    "name": "simulation_end",
    "query": "SELECT  max(start_time) FROM market_orders WHERE simulation = '$simulation' "
   }
  ]
 },
 "panels": [
  {
   "title": "Overview Dashboard",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Welcome to our ASSUME Simulation Comparison Demo\n\nThis is the Grafana Dashboard helps you to compare the results of two simulation. Please note, this dashboard is still under development. Here you can visualize the differences between two simulations. So if some/most of the plots are 0 it just means that the results of your simulation are the same. \n\nYou are currently displaying the difference between:\n##### ${simulation_comp}  -  ${simulation}"
   }
  },
  { "title": "Market Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "options": {
    "content": "# Market-specific Data\n\nData specific for the market depending on the choice made at te top of the panel\n\n"
   }
  },
  {
   "title": "Prices $market ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select sim1.\"time\", sim1.\"Price\" as \"Price $simulation\", sim2.\"Price\" as \"Price $simulation_comp\" , sim2.\"Price\" - sim1.\"Price\" as \"Price Difference\" from (\nSELECT\n  product_start AS \"time\",\n  price AS \"Price\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$simulation') AND (\"market_id\" LIKE '$market') AND $__timeFilter(product_start)\nGROUP BY market_id, simulation, product_start, price\nORDER BY 1) sim1\njoin (\nSELECT\n  product_start AS \"time\",\n  price AS \"Price\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$simulation_comp') AND (\"market_id\" LIKE '$market') AND $__timeFilter(product_start)\nGROUP BY market_id, simulation, product_start, price\nORDER BY 1) sim2 on sim1.time = sim2.time"
    }
   ]
  },
  {
   "title": "Market Summary $market Differences",
   "type": "timeseries",
   "description": "Overview of market results for the chossen market",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select sim1.\"time\", sim2.\"Demand Volume\" - sim1.\"Demand Volume\" as \"Demand Volume Difference\", sim2.\"Supply Volume\" - sim1.\"Supply Volume\" as \"Supply Volume Difference\" from (\nSELECT\n  product_start AS \"time\",\n  demand_volume AS \"Demand Volume\",\n  supply_volume AS \"Supply Volume\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$simulation') AND (\"market_id\" LIKE '$market') AND $__timeFilter(product_start)\nGROUP BY market_id, simulation, product_start, demand_volume, supply_volume\nORDER BY 1\n) sim1\njoin (\nSELECT\n  product_start AS \"time\",\n  demand_volume AS \"Demand Volume\",\n  supply_volume AS \"Supply Volume\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$simulation_comp') AND (\"market_id\" LIKE '$market') AND $__timeFilter(product_start)\nGROUP BY market_id, simulation, product_start, demand_volume, supply_volume\nORDER BY 1\n) sim2 on sim1.\"Demand Volume\" = sim2.\"Demand Volume\""
    },
    {
     "rawSql": "select sim1.\"time\", sim2.\"Price\" - sim1.\"Price\" as \"Price Difference\" from (\nSELECT\n  product_start AS \"time\",\n  price AS \"Price\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$simulation') AND (\"market_id\" LIKE '$market') AND $__timeFilter(product_start)\nGROUP BY market_id, simulation, product_start, price\nORDER BY 1) sim1\njoin (\nSELECT\n  product_start AS \"time\",\n  price AS \"Price\"\nFROM market_meta\nWHERE (\"simulation\" LIKE '$simulation_comp') AND (\"market_id\" LIKE '$market') AND $__timeFilter(product_start)\nGROUP BY market_id, simulation, product_start, price\nORDER BY 1) sim2 on sim1.time = sim2.time"
    }
   ]
  },
  {
   "title": "Accepted Bid Prices Difference",
   "type": "timeseries",
   "description": "Bid prices of accepted bids per unit in the chosen market",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "€/MW" } },
   "targets": [
    {
     "rawSql": "select sim1.\"time\", sim2.\" \" - sim1.\" \" as \"Price\", sim1.bid_id from (\nSELECT\n  $__timeGroupAlias(start_time,$__interval),\n  avg(accepted_price) AS \" \",\n  case\n    when bid_type isnull then concat(unit_id, '_SB')\n    when bid_type != '' then concat(unit_id, '_', bid_type)\n  end AS \"bid_id\"\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  market_id = '$market' AND\n  simulation = '$simulation'\nGROUP BY 1, unit_id, bid_type\nORDER BY 1\n) sim1\njoin (\nSELECT\n  $__timeGroupAlias(start_time,$__interval),\n  avg(accepted_price) AS \" \",\n  case\n    when bid_type isnull then concat(unit_id, '_SB')\n    when bid_type != '' then concat(unit_id, '_', bid_type)\n  end AS \"bid_id\"\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  market_id = '$market' AND\n  simulation = '$simulation'\nGROUP BY 1, unit_id, bid_type\nORDER BY 1) sim2\non sim1.time = sim2.time and sim1.bid_id = sim2.bid_id"
    }
   ]
  },
  {
   "title": "Accepted Bid Volume Difference",
   "type": "timeseries",
   "description": "Accepted Volume  per unit in chosen market",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select sim1.\"time\", sim2.\" \" - sim1.\" \" as \"Volume\", sim1.bid_id from (\nSELECT\n  $__timeGroupAlias(start_time,$__interval),\n  avg(volume) AS \" \",\n  case\n    when bid_type isnull then concat(unit_id, '_SB')\n    when bid_type != '' then concat(unit_id, '_', bid_type)\n  end AS \"bid_id\"\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  market_id = '$market' AND\n  simulation = '$simulation'\nGROUP BY 1, unit_id, bid_type\nORDER BY 1\n) sim1 \njoin (\nSELECT\n  $__timeGroupAlias(start_time,$__interval),\n  avg(volume) AS \" \",\n  case\n    when bid_type isnull then concat(unit_id, '_SB')\n    when bid_type != '' then concat(unit_id, '_', bid_type)\n  end AS \"bid_id\"\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  market_id = '$market' AND\n  simulation = '$simulation'\nGROUP BY 1, unit_id, bid_type\nORDER BY 1\n) sim2 on sim1.time = sim2.time and sim1.bid_id = sim2.bid_id"
    }
   ]
  },
  { "title": "Key performance indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Cost and Volume",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  simulation,\n  sum(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'total_cost') as \"Total cost\",\n  sum(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'total_volume') as \"Total volume\"\nFROM kpis\ngroup by simulation\nORDER BY simulation"
    }
   ]
  },
  {
   "title": "Key indicators",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 10, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  simulation,\n  sum(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'avg_price') as avg_price,\n  sum(round(CAST(value AS numeric), 2))  FILTER (WHERE variable = 'total_cost') as total_cost,\n  sum(round(CAST(value AS numeric), 2)*1000)  FILTER (WHERE variable = 'total_volume') as total_volume\n  \nFROM kpis\nwhere variable in ('total_cost', 'total_volume', 'avg_price')\ngroup by simulation\nORDER BY simulation"
    }
   ]
  },
  {
   "title": "Installed Generation Capacities",
   "type": "piechart",
   "description": "Shows installed capacities in the simulation based on the fuel type",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() as time_sec,\n  SUM(max_power),\n  technology\nFROM power_plant_meta\nWHERE \"simulation\" LIKE '$simulation'\nGROUP BY technology, simulation;\n\n\n"
    }
   ]
  },
  { "title": "Generation units $Gen_Units", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "# Unit Specific Data\n\nFor the chosen market and the chosen unit here the dispatch is displayed."
   }
  },
  {
   "title": "Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select sim1.\"time\", sim2.\"market_dispatch\" - sim1.\"market_dispatch\" as \"market_dispatch\", sim1.unit_id, sim1.market_id from (\nSELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"market_dispatch\",\n  unit_id,\n  market_id\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  simulation = '$simulation' AND\n  unit_id in ($Gen_Units)\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1\n) sim1\nleft join (\nSELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"market_dispatch\",\n  unit_id,\n  market_id\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  simulation = '$simulation_comp' AND\n  unit_id in ($Gen_Units)\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1\n) sim2\non sim1.unit_id = sim2.unit_id and sim1.market_id = sim2.market_id and sim1.time=sim2.time"
    },
    {
     "rawSql": "select sim1.\"time\", sim2.\"dispatch\" - sim1.\"dispatch\" as \"dispatch\", sim1.unit from (\nSELECT\n  $__timeGroupAlias(time,$__interval),\n  power AS \"dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(time) AND\n  simulation = '$simulation' AND\n  unit in ($Gen_Units)\nGROUP BY 1, unit, power\nORDER BY 1\n) sim1\nleft join (\nSELECT\n  $__timeGroupAlias(time,$__interval),\n  power AS \"dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(time) AND\n  simulation = '$simulation_comp' AND\n  unit in ($Gen_Units)\nGROUP BY 1, unit, power\nORDER BY 1\n) sim2\non sim1.unit = sim2.unit and sim1.time=sim2.time"
    }
   ]
  },
  {
   "title": "Chosen Unit Specifications",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 53 },
   "options": {
    "content": "### General Information\n\nName: {{index}} <br>\nTechnology: {{technology}} <br>\n\n### Technical Specifications\nEmissions: {{emission_factor}} t/MWh <br>\nMaximum Power: {{max_power}} MW <br>\nMinimum Power: {{min_power}} MW <br>\nEfficiency: {{efficiency}} <br>\n\n##### Unit Operator: {{unit_operator}}\n  "
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM power_plant_meta\nWHERE index in ($Gen_Units) and simulation = '$simulation'\n"
    }
   ]
  },
  {
   "title": "Accepted Bid Prices",
   "type": "timeseries",
   "description": "Bid prices of accepted bids per unit in the chosen market",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select sim1.\"time\", sim2.\"price\" - sim1.\"price\" as \"price\", sim2.\"volume\" - sim1.\"volume\" as \"volume\", sim1.unit_id from (\nselect\n  $__timeGroupAlias(start_time,$__interval),\n  avg(accepted_price) AS \"price\",\n  avg(volume) AS \"volume\",\n  concat(unit_id, ' - ', market_id) as \"unit_id\"\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  unit_id in ($Gen_Units) AND\n  simulation = '$simulation'\nGROUP BY 1, unit_id, market_id\nORDER BY 1\n) sim1\nleft join (\nSELECT\n  $__timeGroupAlias(start_time,$__interval),\n  avg(accepted_price) AS \"price\",\n  avg(volume) AS \"volume\",\n  concat(unit_id, ' - ', market_id) as \"unit_id\"\nFROM market_orders\nWHERE\n  $__timeFilter(start_time) AND\n  unit_id in ($Gen_Units) AND\n  simulation = '$simulation_comp'\nGROUP BY 1, unit_id, market_id\nORDER BY 1\n) sim2\non sim1.time = sim2.time and sim1.unit_id = sim2.unit_id"
    }
   ]
  },
  {
   "title": "Demand units data $Demand_Units",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 71 },
   "options": {
    "content": "# Unit Specific Data\n\nFor the chosen market and the chosen unit here the dispatch is displayed."
   }
  },
  {
   "title": "Unitwise Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select sim1.\"time\", sim2.\"power\" - sim1.\"power\" as \"power\", sim1.unit_id, sim1.market_id from (\nSELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"power\",\n  unit_id,\n  market_id\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  simulation = '$simulation' AND\n  unit_id in ($Demand_Units)\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1\n) sim1 left join\n(SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"power\",\n  unit_id,\n  market_id\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  simulation = '$simulation_comp' AND\n  unit_id in ($Demand_Units)\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1) sim2\non sim1.unit_id = sim2.unit_id and sim1.market_id = sim2.market_id and sim1.time=sim2.time"
    },
    {
     "rawSql": "select sim1.\"time\", sim2.\"dispatch\" - sim1.\"dispatch\" as \"dispatch\", sim1.unit from (\nSELECT\n  $__timeGroupAlias(time,$__interval),\n  power AS \"dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(time) AND\n  simulation = '$simulation' AND\n  unit in ($Demand_Units)\nGROUP BY 1, unit, power\nORDER BY 1\n) sim1\nleft join (\nSELECT\n  $__timeGroupAlias(time,$__interval),\n  power AS \"dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(time) AND\n  simulation = '$simulation_comp' AND\n  unit in ($Demand_Units)\nGROUP BY 1, unit, power\nORDER BY 1\n) sim2\non sim1.unit = sim2.unit and sim1.time=sim2.time"
    }
   ]
  },
  {
   "title": "Chosen Unit Specifications",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 74 },
   "options": {
    "content": "### General Information\n\nName: {{index}} <br>\nTechnology: {{technology}} <br>\n\n### Technical Specifications\nEmissions: {{emission_factor}} t/MWh <br>\nMaximum Power: {{max_power}} MW <br>\nMinimum Power: {{min_power}} MW <br>\nEfficiency: {{efficiency}} <br>\n\n##### Unit Operator: {{unit_operator}}\n  "
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM demand_meta\nWHERE index in ($Demand_Units) and simulation = '$simulation'\n"
    }
   ]
  },
  {
   "title": "Storage units data $Storage_Units",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "repeat": "Storage_Units"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 84 },
   "options": {
    "content": "# Unit Specific Data\n\nFor the chosen market and the chosen storage unit here the dispatch is displayed."
   }
  },
  {
   "title": "Storage Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "select sim1.\"time\", sim2.\"power\" - sim1.\"power\" as \"power\", sim1.unit_id, sim1.market_id from (\nSELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"power\",\n  unit_id,\n  market_id\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  simulation = '$simulation' AND\n  unit_id in ($Storage_Units)\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1\n) sim1 join\n(SELECT\n  $__timeGroupAlias(datetime,$__interval),\n  power AS \"power\",\n  unit_id,\n  market_id\nFROM market_dispatch\nWHERE\n  $__timeFilter(datetime) AND\n  simulation = '$simulation_comp' AND\n  unit_id in ($Storage_Units)\nGROUP BY 1, unit_id, power, market_id\nORDER BY 1) sim2\non sim1.unit_id = sim2.unit_id and sim1.market_id = sim2.market_id and sim1.time=sim2.time"
    },
    {
     "rawSql": "select sim1.\"time\", sim2.\"dispatch\" - sim1.\"dispatch\" as \"dispatch\", sim1.unit from (\nSELECT\n  $__timeGroupAlias(time,$__interval),\n  power AS \"dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  simulation = '$simulation' AND\n  unit in ($Storage_Units)\nGROUP BY 1, unit, power\nORDER BY 1\n) sim1\njoin (\nSELECT\n  $__timeGroupAlias(time,$__interval),\n  power AS \"dispatch\",\n  unit\nFROM unit_dispatch\nWHERE\n  $__timeFilter(index) AND\n  simulation = '$simulation_comp' AND\n  unit in ($Storage_Units)\nGROUP BY 1, unit, power\nORDER BY 1\n) sim2\non sim1.unit = sim2.unit and sim1.time=sim2.time"
    }
   ]
  },
  {
   "title": "Chosen Unit Specifications",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 87 },
   "options": {
    "content": "### General Information\n\nName: {{index}} <br>\nTechnology: {{technology}} <br>\n\n### Technical Specifications\nEmissions: {{emission_factor}} t/MWh_thermal <br>\nCapacity: {{capacity}} MWh <br>\nMaximum Power Disharge: {{max_power_discharge}} MW <br>\nMinimum Power Discharge: {{min_power_discharge}} MW <br>\nEfficiency Discharge: {{efficiency_discharge}} % <br>\n\nMaximum Power Charge: {{max_power_charge}} MW <br>\nMinimum Power Charge: {{min_power_charge}} MW <br>\nEfficiency Charge: {{efficiency_charge}} % <br>\n\n##### Unit Operator: {{unit_operator}}\n  "
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM storage_meta\nWHERE index in ($Storage_Units) and simulation = '$simulation'\n"
    }
   ]
  }
 ]
}