# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: PR Agent
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, review_requested]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' && (github.event_name == 'pull_request' || github.event.issue.pull_request) }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent action step
        uses: the-pr-agent/pr-agent@v0.36.1
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG__FALLBACK_MODELS: '["openai/openai-gpt-oss-120b"]'
          CONFIG__CUSTOM_MODEL_MAX_TOKENS: "128000"
          OPENAI__API_BASE: "https://chat.kiconnect.nrw/api/v1"
          CONFIG__MODEL: "openai/gpt-5.2"
          github_action_config.pr_actions: '["opened", "reopened", "synchronize", "ready_for_review", "review_requested"]'
