# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'

    - name: Check reuse compliance
      run: |
        pip install reuse
        reuse lint

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test,learning,network,oeds]

    - name: Lint with ruff
      run: |
        ruff check assume assume_cli tests
        ruff format assume assume_cli tests

    - name: Test with pytest
      run: |
        pytest --cov --cov-report=xml --junitxml="result.xml"

    - name: Build package
      run: |
        python -m pip install build
        python -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  pypi-publish:
    name: Upload release to PyPI
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/assume-framework
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
